// <auto-generated />
using System;
using EasyFinance.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyFinance.Migrations
{
    [DbContext(typeof(EasyFinanceDbContext))]
    [Migration("20200326172108_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyFinance.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Продукти"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Сніданок"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Обід"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Вечеря"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Таксі/Автобус"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Потяг"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Книги/Журнали"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Подарунок"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Дозвілля"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Одяг"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Бензин"
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Інше"
                        });
                });

            modelBuilder.Entity("EasyFinance.DataAccess.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenericCode");

                    b.Property<string>("MatchPattern");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenericCode = "UAH",
                            MatchPattern = " ?грн.? ?",
                            Name = "Hryvnia"
                        },
                        new
                        {
                            Id = 2,
                            GenericCode = "EUR",
                            Name = "Euro"
                        },
                        new
                        {
                            Id = 3,
                            GenericCode = "USD",
                            Name = "US Dollar"
                        });
                });

            modelBuilder.Entity("EasyFinance.DataAccess.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MatchPattern");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MatchPattern = "г[ao]тівк[а]",
                            Name = "Готівка"
                        },
                        new
                        {
                            Id = 2,
                            MatchPattern = "(к[ао]ртк[ао]|безг[ао]тівк[ао]в[ао])",
                            Name = "Картка"
                        });
                });

            modelBuilder.Entity("EasyFinance.DataAccess.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<int?>("CurrencyId");

                    b.Property<int?>("PaymentMethodId");

                    b.Property<DateTime?>("PurchaseDate");

                    b.Property<decimal?>("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("EasyFinance.DataAccess.Entities.ReceiptPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("FileBytes");

                    b.Property<string>("FileName");

                    b.Property<int?>("ReceiptId");

                    b.HasKey("Id");

                    b.ToTable("ReceiptPhotos");
                });

            modelBuilder.Entity("EasyFinance.DataAccess.Entities.Receipt", b =>
                {
                    b.HasOne("EasyFinance.DataAccess.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("EasyFinance.DataAccess.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("EasyFinance.DataAccess.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");
                });
#pragma warning restore 612, 618
        }
    }
}
